In [56]:
import plotly.graph_objects as go
import numpy as np

labels = ["apples","oranges","pears","bananas"]
widths = np.array([10,10,10,10])
heights = np.array([20] * 5)
data = {
    "South": [50,80,60,70],
    "North": [50,20,40,30]
}

fig = go.Figure()
for key in data:
    fig.add_trace(go.Bar(
        name=key,
        y=data[key],
        x=np.cumsum(widths)-widths,
        width=widths,
        offset=0,
        customdata=np.transpose([labels, widths*data[key]]),
        texttemplate="%{y} x %{width} =<br>%{customdata[1]}",
        textposition="inside",
        textangle=0,
        textfont_color="white",
        hovertemplate='',

#         hovertemplate="<br>".join([
#             "label: %{customdata[0]}",
#             "width: %{width}",
#             "height: %{y}",
#             "area: %{customdata[1]}",
#         ])
    ))

fig.update_xaxes(
    tickvals=np.cumsum(widths)-widths/2,
    ticktext= ["%s<br>%d" % (l, w) for l, w in zip(labels, widths)]
)

fig.update_xaxes(range=[0,100])
fig.update_yaxes(range=[0,100])

fig.update_layout(
    title_text="Marimekko Chart",
    barmode="stack",
    uniformtext=dict(mode="hide", minsize=10),
)



In [34]:
import seaborn as sns

In [35]:
# np.transpose([labels, widths*data[key]]),

In [36]:
# [labels, widths*data[key]]

In [37]:
import pandas as pd
import numpy as np

In [38]:
col = ["AXS","ALICE"]
ids = ["30s","1","2","3","5"]
data = np.zeros([len(ids),len(col)])
data = np.linspace(0,9,10).reshape([5,2])
df = pd.DataFrame(data,columns=col,index=ids)

In [39]:
df

AXS  ALICE
30s  0.0    1.0
1    2.0    3.0
2    4.0    5.0
3    6.0    7.0
5    8.0    9.0

In [40]:
df

AXS  ALICE
30s  0.0    1.0
1    2.0    3.0
2    4.0    5.0
3    6.0    7.0
5    8.0    9.0

In [41]:
class ColorTranslator:

    def init_color_palette(self, n):
        c = sns.diverging_palette(0, 150, s=140, l=50, n=n, as_cmap=False)
        # cs = dict(zip(range(0, n), list(map(lambda x:'rgba({},{},{},0.7)'.format,list(map(lambda x: np.array(x) * 255, c))))))
        cs = dict(zip(range(0, n), map(lambda x: np.array(x) * 255, c)))
        # cs = dict(zip(range(0, n), c))
        self.n = n
        self.cs = cs
        print(cs)

    def apply(self, df):
        self.ma = df.values.max()
        self.mi = df.values.min()
#         self.f = lambda x:math.ceil(((self.n-1)/(self.ma-self.mi))*x)
        self.f = lambda x:math.ceil(((self.n-1)/(self.ma-self.mi))*(x-self.mi))

    def get_color(self,values):
        a = list(map(self.cs.get, list(map(self.f, values))))
        print(a)
        result = ['rgba({},{},{},0.7)'.format(*x) for x in a]
        # return list(map(lambda x:'rgba({},{},{},0.7)'.format,)))
        return result





In [42]:
df

AXS  ALICE
30s  0.0    1.0
1    2.0    3.0
2    4.0    5.0
3    6.0    7.0
5    8.0    9.0

In [64]:
df['AXS']['2'] = -2.5
df['AXS']['3'] = -10.3

In [65]:
df

AXS  ALICE
30s   0.0    1.0
1     2.0    3.0
2    -2.5    5.0
3   -10.3    7.0
5     8.0    9.0

In [66]:
ct = ColorTranslator()
ct.init_color_palette(31)
ct.apply(df)

{0: array([255.        ,   0.        ,  91.70330079]), 1: array([254.23289958,  15.11507696, 101.05928217]), 2: array([253.3699116 ,  32.11953855, 111.58476122]), 3: array([252.60281117,  47.23461551, 120.94074259]), 4: array([251.7398232 ,  64.2390771 , 131.46622164]), 5: array([250.97272277,  79.35415406, 140.82220302]), 6: array([250.10973479,  96.35861564, 151.34768207]), 7: array([249.34263437, 111.47369261, 160.70366345]), 8: array([248.43188989, 129.4191563 , 171.81160716]), 9: array([247.66478947, 144.53423326, 181.16758853]), 10: array([246.80180149, 161.53869485, 191.69306758]), 11: array([246.03470107, 176.65377181, 201.04904896]), 12: array([245.17171309, 193.65823339, 211.57452801]), 13: array([244.40461267, 208.77331036, 220.93050939]), 14: array([243.54162469, 225.77777194, 231.45598843]), 15: array([238.06552992, 242.57908371, 239.4869395 ]), 16: array([220.09296468, 236.91850825, 227.58969904]), 17: array([203.51665458, 229.73774238, 216.60849878]), 18: array([188.7821

In [67]:
import math

In [68]:



fig = go.Figure()
for key in df.index[::-1]:
    fig.add_trace(go.Bar(
        name=key,
        y=[20]*df.shape[1],
        x=np.cumsum(widths)-widths,
        width=widths,
        offset=0,
        customdata=df.loc[key,:].values,
        texttemplate="%{customdata}",
#         marker_color=colors[t]
        marker_color=ct.get_color(df.loc[key,:]),
        textposition="inside",
        textangle=0,
        textfont_color="white",
        hovertemplate='',
    ))

fig.update_xaxes(
    tickvals=np.cumsum(widths)-widths/2,
#     tickvals=np.cumsum(widths)-widths/2,
    
    ticktext= ["%s" % (l) for l in zip(df.columns)]
)
fig.update_yaxes(
    tickvals=np.cumsum(heights)-heights/2,
#     tickvals=np.cumsum(widths)-widths/2,
    
    ticktext= ["%s" % (l) for l in zip(df.columns)]
)

fig.update_xaxes(range=[0,100])
# fig.update_yaxes(df.index)

fig.update_layout(
    title_text="Marimekko Chart",
    barmode="stack",
    uniformtext=dict(mode="hide", minsize=10),
    template='plotly_dark'
)
# print(widths)

[array([ 14.73449787, 147.95835608,  91.54721217]), array([  0.        , 141.57545309,  81.78614527])]
[array([255.        ,   0.        ,  91.70330079]), array([ 46.04530585, 161.52202495, 112.28947934])]
[array([244.40461267, 208.77331036, 220.93050939]), array([ 93.93242394, 182.26645968, 144.01294677])]
[array([157.47134872, 209.79117052, 186.10516471]), array([140.89503862, 202.61040465, 175.12396444])]
[array([203.51665458, 229.73774238, 216.60849878]), array([188.7821567 , 223.35483938, 206.84743187])]


In [60]:
widths

array([10, 10, 10, 10])

In [62]:
np.cumsum(heights)-heights/2

array([10., 30., 50., 70., 90.])

In [55]:
np.cumsum(widths)

array([10, 20, 30, 40], dtype=int32)

In [17]:
import plotly.express as px
colorscales = px.colors.named_colorscales()

In [18]:
col = ["AXS","ALICE"]
ids = ["30s","1","2","3","5"]
data = np.zeros([len(ids),len(col)])
data = np.linspace(0,10,10).reshape([5,2])
df = pd.DataFrame(data,columns=col,index=ids)

In [19]:
dft = df.T

In [20]:
dft["h"] = [20,20]

In [21]:
dft

30s         1         2         3          5   h
AXS    0.000000  2.222222  4.444444  6.666667   8.888889  20
ALICE  1.111111  3.333333  5.555556  7.777778  10.000000  20

In [22]:
import plotly.express as px

wide_df = px.data.medals_wide()

fig = px.bar(dft, x=dft.index, y=['h']*5,color = ["30s","1"], title="Wide-Form Input")
fig.show()

In [23]:
wide_df

nation  gold  silver  bronze
0  South Korea    24      13      11
1        China    10      15       8
2       Canada     9      12      12

In [24]:
import pandas as pd
import plotly.express as px
import plotly.graph_objs as go

# data
d = {'Scenario': [1, 2, 3, 1, 2,3],
     'Type': ["A", "A", "A", "B", "B", "B"],
     'VAL_1': [100, 200, 300, 400 , 500, 600],
     'VAL_2': [1000, 2000, 3000, 4000, 5000, 6000]}
df = pd.DataFrame(data=d)

# assign colors to type using a dictionary
colors = {'A':'steelblue',
          'B':'firebrick'}

# plotly figure
fig=go.Figure()
for t in df['Type'].unique():
    dfp = df[df['Type']==t]
    fig.add_traces(go.Bar(x=dfp['Scenario'], y = dfp['VAL_1'], name=t,
                         marker_color=colors[t]))

fig.show()

In [25]:
import pandas as pd
import plotly.express as px
import plotly.graph_objs as go

# data
d = {'Scenario': [1, 2, 3, 1, 2,3],
     'Type': ["A", "A", "A", "B", "B", "B"],
     'VAL_1': [100, 200, 300, 400 , 500, 600],
     'VAL_2': [1000, 2000, 3000, 4000, 5000, 6000]}
df = pd.DataFrame(data=d)

# assign colors to type using a dictionary
colors = {'A':'steelblue',
          'B':'firebrick'}


colors1 = ["steelblue","red","orange"]

colors2 = ["rgba(180,88,88,0.4)"]*3

# plotly figure
fig=go.Figure()
for t in df['Type'].unique():
    dfp = df[df['Type']==t]
    fig.add_traces(go.Bar(x=dfp['Scenario'], y = dfp['VAL_1'], name=t,
                         marker_color=colors2))

fig.show()

In [26]:
df

Scenario Type  VAL_1  VAL_2
0         1    A    100   1000
1         2    A    200   2000
2         3    A    300   3000
3         1    B    400   4000
4         2    B    500   5000
5         3    B    600   6000

In [27]:

import seaborn as sns

In [28]:
 sns.color_palette

<function seaborn.palettes.color_palette(palette=None, n_colors=None, desat=None, as_cmap=False)>

In [29]:
c = sns.diverging_palette(0,150,s=140,l=50,n=21,as_cmap=False)


In [30]:
c

[(1.0, 0.0, 0.35962078741086706),
 (0.9954876445611134, 0.0889122174335248, 0.4146559719818968),
 (0.9905992595023196, 0.18523378631984333, 0.47427742193384576),
 (0.9857108744435258, 0.2815553552061619, 0.5338988718857948),
 (0.980822489384732, 0.3778769240924804, 0.5935203218377436),
 (0.9757468239488359, 0.47788869731563954, 0.65542594693058),
 (0.9712344685099493, 0.5668009147491644, 0.7104611315016098),
 (0.9663460834511556, 0.6631224836354829, 0.7700825814535588),
 (0.9614576983923617, 0.7594440525218015, 0.8297040314055077),
 (0.9565693133335679, 0.85576562140812, 0.8893254813574566),
 (0.9335903134210628, 0.951290524359234, 0.939164468620433),
 (0.8342184931227664, 0.916576693135938, 0.873369276821214),
 (0.7403221831502437, 0.8759013309134184, 0.8111663995062834),
 (0.6464258731777209, 0.8352259686908988, 0.748963522191353),
 (0.5525295632051981, 0.7945506064683792, 0.6867606448764224),
 (0.45592470582962186, 0.7527019164894408, 0.6227634537927921),
 (0.3683624468152816, 0.7147704301139631, 0.56475665398904),
 (0.2744661368427589, 0.6740950678914437, 0.5025537766741095),
 (0.1805698268702361, 0.633419705668924, 0.44035089935917887),
 (0.08667351689771327, 0.5927443434464045, 0.3781480220442483),
 (0.0, 0.5551978552410017, 0.320729981445851)]

In [31]:
cs = dict(zip(range(0,21), c))


In [32]:
cs

{0: (1.0, 0.0, 0.35962078741086706),
 1: (0.9954876445611134, 0.0889122174335248, 0.4146559719818968),
 2: (0.9905992595023196, 0.18523378631984333, 0.47427742193384576),
 3: (0.9857108744435258, 0.2815553552061619, 0.5338988718857948),
 4: (0.980822489384732, 0.3778769240924804, 0.5935203218377436),
 5: (0.9757468239488359, 0.47788869731563954, 0.65542594693058),
 6: (0.9712344685099493, 0.5668009147491644, 0.7104611315016098),
 7: (0.9663460834511556, 0.6631224836354829, 0.7700825814535588),
 8: (0.9614576983923617, 0.7594440525218015, 0.8297040314055077),
 9: (0.9565693133335679, 0.85576562140812, 0.8893254813574566),
 10: (0.9335903134210628, 0.951290524359234, 0.939164468620433),
 11: (0.8342184931227664, 0.916576693135938, 0.873369276821214),
 12: (0.7403221831502437, 0.8759013309134184, 0.8111663995062834),
 13: (0.6464258731777209, 0.8352259686908988, 0.748963522191353),
 14: (0.5525295632051981, 0.7945506064683792, 0.6867606448764224),
 15: (0.45592470582962186, 0.752701916489

In [70]:
sns.diverging_palette(0, 150, s=140, l=50, n=10, as_cmap=False)

[(1.0, 0.0, 0.35962078741086706),
 (0.9894711706425979, 0.20746184067822454, 0.48803621807660325),
 (0.978942341285196, 0.414923681356449, 0.6164516487423395),
 (0.9678502019307844, 0.633485077824308, 0.7517375199298821),
 (0.9573213725733823, 0.8409469185025326, 0.8801529505956183),
 (0.8197729069731475, 0.9103189451017042, 0.8637996033881478),
 (0.6175347008784832, 0.8227104726224312, 0.7298241753252205),
 (0.40447641218932884, 0.7304148001995476, 0.5886808375717055),
 (0.20223820609466442, 0.6428063277202747, 0.45470540950877825),
 (0.0, 0.5551978552410017, 0.320729981445851)]

In [53]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Create figure with secondary y-axis
fig = make_subplots(specs=[[{"secondary_y": True}]])

# Add traces
fig.add_trace(
    go.Scatter(x=[1, 2, 3], y=[40, 50, 60], name="yaxis data"),
    secondary_y=False,
)

fig.add_trace(
    go.Scatter(x=[2, 3, 4], y=[4, 5, 6], name="yaxis2 data"),
    secondary_y=True,
)

# Add figure title
fig.update_layout(
    title_text="Double Y Axis Example"
)

# Set x-axis title
fig.update_xaxes(title_text="xaxis title")

# Set y-axes titles
fig.update_yaxes(title_text="<b>primary</b> yaxis title", secondary_y=False)
fig.update_yaxes(title_text="<b>secondary</b> yaxis title", secondary_y=True, showgrid= False)

fig.show()